# Generated by Django 5.0.7 on 2024-09-07 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_refreshtokens'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RefreshTokens',
        ),
    ]
