# Generated by Django 5.0.7 on 2024-09-14 03:21

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(default='Point', max_length=50)),
                ('coordinates', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=2)),
                ('address', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('point_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tours.point')),
                ('day', models.IntegerField()),
            ],
            options={
                'ordering': ['day'],
            },
            bases=('tours.point',),
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('max_group_size', models.IntegerField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('difficult', 'Difficult')], max_length=10)),
                ('ratings_average', models.DecimalField(decimal_places=2, default=4.5, max_digits=3)),
                ('ratings_quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('image_cover', models.ImageField(upload_to='tours/covers/')),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None)),
                ('start_dates', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), size=None)),
                ('guides', models.ManyToManyField(related_name='tours', to=settings.AUTH_USER_MODEL)),
                ('start_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours_starting', to='tours.point')),
                ('locations', models.ManyToManyField(related_name='tours', to='tours.location')),
            ],
            options={
                'ordering': ['-ratings_average'],
            },
        ),
    ]
