# Generated by Django 5.0.7 on 2024-08-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.IntegerField()),
                ('maxGroupSize', models.IntegerField()),
                ('difficulty', models.CharField(max_length=50)),
                ('ratingsAverage', models.DecimalField(decimal_places=1, default=4.5, max_digits=2)),
                ('ratingsQuantity', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('imageCover', models.ImageField(upload_to='tours/')),
                ('startDates', models.JSONField()),
            ],
        ),
    ]
